#!/usr/bin/env python3
"""pip-lock.py — turn a pinned closure (*.in) into a --require-hashes file (*.txt).

@decision DEC-PHASE12-116
@title Build-time pip installs come from committed, hash-locked closures
@status accepted
@rationale The 0500 hook installed volatility3, stix2/pyfiglet, flare-capa and
  matrix-commander unpinned, so two builds of one commit could ship different
  code and a compromised PyPI release would land in a root-capable image
  without a repo change (packages-build P2-4, security F13). Each install now
  reads iso/config/includes.chroot/usr/share/orionx/pip/<set>.txt with
  `pip install --require-hashes --no-deps -r`. The closures (<set>.in) are
  the exact versions the v2.2.0-rc9 build resolved (its log, "Successfully
  installed ..."), minus deliberate exclusions noted in each .in file. This
  tool adds every sha256 PyPI publishes for each pinned release (wheels for
  all platforms and the sdist), so a pip on any platform can satisfy the lock;
  it never resolves or changes a version. Regenerate after editing a .in:
      python3 scripts/release/pip-lock.py iso/config/includes.chroot/usr/share/orionx/pip/*.in
  then rebuild and run the venv smoke test the hook runs (tool --version).
  The lock files ship in the image at /usr/share/orionx/pip/ as the record
  of what was installed.
"""
import json
import pathlib
import re
import sys
import urllib.request

LINE = re.compile(r"^([A-Za-z0-9_.\-]+)==([A-Za-z0-9_.+\-!]+)$")


def hashes(name, version):
    url = f"https://pypi.org/pypi/{name}/{version}/json"
    with urllib.request.urlopen(url, timeout=60) as r:
        data = json.load(r)
    found = sorted({u["digests"]["sha256"] for u in data["urls"]})
    if not found:
        raise SystemExit(f"ERROR: PyPI lists no files for {name}=={version}")
    return found


def lock(src):
    src = pathlib.Path(src)
    out = src.with_suffix(".txt")
    header, pins = [], []
    for raw in src.read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            header.append(raw)
            continue
        m = LINE.match(line)
        if not m:
            raise SystemExit(f"ERROR: {src}: not an exact name==version pin: {raw!r}")
        pins.append(m.groups())
    lines = [f"# GENERATED by scripts/release/pip-lock.py from {src.name}; do not edit.",
             "# Install: pip install --no-input --require-hashes --no-deps -r <this file>"]
    lines += [h for h in header if h.strip()]
    for name, version in pins:
        hs = hashes(name, version)
        lines.append(f"{name}=={version} \\")
        lines += [f"    --hash=sha256:{h} \\" for h in hs[:-1]]
        lines.append(f"    --hash=sha256:{hs[-1]}")
    out.write_text("\n".join(lines) + "\n")
    print(f"{out}: {len(pins)} packages locked")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        raise SystemExit("usage: pip-lock.py <set>.in [...]")
    for arg in sys.argv[1:]:
        lock(arg)
