"""
Canonical path constants for the Nebula runtime.

All path literals that Nebula Python uses live here — helpers, services, and
the CLI all import from this module. A single change here propagates everywhere.

@decision DEC-PHASE10-009
@title Single authority for all Nebula runtime paths
@status accepted
@rationale Scattered path literals across modules produce silent drift when the
  chroot layout changes (e.g. a future relocation of /opt/orionx/nebula/).
  Centralising in helpers/paths.py makes the layout a single-grep audit.
"""
from __future__ import annotations

from pathlib import Path

# ---------------------------------------------------------------------------
# Production paths (chroot layout; also used at runtime on the booted ISO)
# ---------------------------------------------------------------------------

# Base installation root for Nebula assets staged by stage_nebula_model()
NEBULA_BASE: Path = Path("/opt/orionx/nebula")

# Model storage dir: where the GGUF and MANIFEST.sha256 live after staging.
# stage_nebula_model() writes here; integrity.py reads here.
MODELS_DIR: Path = NEBULA_BASE / "models"

# MANIFEST.sha256: sha256sum-compatible file generated by stage_nebula_model().
# integrity.py verifies the model file against this manifest at boot.
MANIFEST_FILE: Path = MODELS_DIR / "MANIFEST.sha256"

# Nebula scripts root (staged by stage_application_content via scripts/ rsync)
SCRIPTS_ROOT: Path = Path("/opt/orionx/scripts/nebula")

# ---------------------------------------------------------------------------
# Runtime state paths (on the live system; tmpfs under /run/; dirs created by
# nebula-integrity-check.service ExecStartPre=/bin/mkdir -p /run/orionx)
# ---------------------------------------------------------------------------

# Written by integrity.py; read by the Control Center Nebula section widget.
INTEGRITY_STATUS_FILE: Path = Path("/run/orionx/nebula-integrity.status")

# ---------------------------------------------------------------------------
# Log paths — all Nebula logs go under /var/log/orionx/
# ---------------------------------------------------------------------------
LOG_DIR: Path = Path("/var/log/orionx")
INTEGRITY_LOG: Path = LOG_DIR / "nebula-integrity.log"
RUNTIME_LOG: Path = LOG_DIR / "nebula-runtime.log"
WARMUP_LOG: Path = LOG_DIR / "nebula-warmup.log"

# ---------------------------------------------------------------------------
# ollama API endpoint (localhost-only; DEC-006 LOCAL-ONLY)
# ---------------------------------------------------------------------------
OLLAMA_HOST: str = "127.0.0.1"
OLLAMA_PORT: int = 11434
OLLAMA_BASE_URL: str = f"http://{OLLAMA_HOST}:{OLLAMA_PORT}"
