name: Lint

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install shellcheck
        run: sudo apt-get install -y shellcheck

      - name: Run lint
        run: make lint
